
import { Subject } from './types';

export const INITIAL_SUBJECTS: Subject[] = [
  { id: 'ext-th', name: 'Agriculture Extension', type: 'Theory', isPracticalEnabled: false },
  { id: 'chem-th', name: 'Agricultural Chemistry', type: 'Theory', isPracticalEnabled: true },
  { id: 'chem-pr', name: 'Agricultural Chemistry (Practical)', type: 'Practical', isPracticalEnabled: true },
  { id: 'agro-th', name: 'Agronomy', type: 'Theory', isPracticalEnabled: true },
  { id: 'agro-pr', name: 'Agronomy (Practical)', type: 'Practical', isPracticalEnabled: true },
  { id: 'eng-th', name: 'English', type: 'Theory', isPracticalEnabled: false },
  { id: 'soc-th', name: 'Sociology', type: 'Theory', isPracticalEnabled: false },
  { id: 'cs-th', name: 'Computer Science', type: 'Theory', isPracticalEnabled: true },
  { id: 'cs-pr', name: 'Computer Science (Practical)', type: 'Practical', isPracticalEnabled: true },
  { id: 'islam-th', name: 'Islamic Studies', type: 'Theory', isPracticalEnabled: false },
];

export const MOCK_STUDENTS = [
  { id: 's1', name: 'Muhammad Taufeeq Khan', rollNumber: '1', photoUrl: 'https://i.pravatar.cc/150?u=s1' },
  { id: 's2', name: 'Huzaifa Usman', rollNumber: '2', photoUrl: 'https://i.pravatar.cc/150?u=s2' },
  { id: 's3', name: 'Selab', rollNumber: '3', photoUrl: 'https://i.pravatar.cc/150?u=s3' },
  { id: 's4', name: 'Awad Badar', rollNumber: '4', photoUrl: 'https://i.pravatar.cc/150?u=s4' },
  { id: 's5', name: 'Waqas Uddin', rollNumber: '5', photoUrl: 'https://i.pravatar.cc/150?u=s5' },
  { id: 's6', name: 'Ishtiaq Ahmad', rollNumber: '6', photoUrl: 'https://i.pravatar.cc/150?u=s6' },
  { id: 's7', name: 'Shahab Ud Din', rollNumber: '7', photoUrl: 'https://i.pravatar.cc/150?u=s7' },
  { id: 's8', name: 'Kamran Khan', rollNumber: '8' },
  { id: 's9', name: 'Hasan Shah', rollNumber: '9' },
  { id: 's10', name: 'Muhammad Atif', rollNumber: '10' },
  { id: 's11', name: 'Abdullah Shah', rollNumber: '11' },
  { id: 's12', name: 'Zayrab Sabir', rollNumber: '12' },
  { id: 's13', name: 'Adil Raza', rollNumber: '13' },
  { id: 's14', name: 'Shehriyar Hassan', rollNumber: '14' },
  { id: 's15', name: 'Haroon Ur Rashid', rollNumber: '15' },
  { id: 's16', name: 'Aftab Khan', rollNumber: '16' },
  { id: 's17', name: 'Muhammad Ismail', rollNumber: '17' },
  { id: 's18', name: 'Hamza Aftab', rollNumber: '18' },
  { id: 's19', name: 'Abdul Khaliq', rollNumber: '19' },
  { id: 's20', name: 'Uzair Ahmad', rollNumber: '20' },
  { id: 's21', name: 'Gulzar Nawaz Ahmad', rollNumber: '21' },
  { id: 's22', name: 'Raz Uddin', rollNumber: '22' },
  { id: 's23', name: 'Ihtisham Ul Haq', rollNumber: '23' },
  { id: 's24', name: 'Abdurraheem', rollNumber: '24' },
  { id: 's25', name: 'Syed Muneeb Shah', rollNumber: '25' },
  { id: 's26', name: 'Muhammad Zubair', rollNumber: '26' },
  { id: 's27', name: 'Imdad Ullah', rollNumber: '27' },
  { id: 's28', name: 'Saqibur Rahman', rollNumber: '28' },
  { id: 's29', name: 'Hasanain Khan', rollNumber: '29' },
  { id: 's30', name: 'Noor Eman', rollNumber: '30' },
  { id: 's31', name: 'Memoona Jahan', rollNumber: '31' },
  { id: 's32', name: 'Ayesha', rollNumber: '32' },
  { id: 's33', name: 'Marwa Ahmed', rollNumber: '33' },
  { id: 's34', name: 'Sawaira Syed', rollNumber: '34' },
  { id: 's35', name: 'Isbah Naseem', rollNumber: '35' },
  { id: 's36', name: 'Rania Gul Mohmand', rollNumber: '36' },
  { id: 's37', name: 'Syeda Abeeha Shah', rollNumber: '37' },
  { id: 's38', name: 'Alishba Fari', rollNumber: '38' },
  { id: 's39', name: 'Iram Bibi', rollNumber: '39' },
  { id: 's40', name: 'Sanoodiya', rollNumber: '40' },
  { id: 's41', name: 'Manahil', rollNumber: '41' },
  { id: 's42', name: 'Syeda Malaika Jehangir', rollNumber: '42' },
  { id: 's43', name: 'Marwa Khalil', rollNumber: '43' },
  { id: 's44', name: 'Hira Bibi', rollNumber: '44' },
  { id: 's45', name: 'Mahrukh Fatima', rollNumber: '45' },
  { id: 's46', name: 'Masood Khan', rollNumber: '46' },
  { id: 's47', name: 'Muhammad Omer', rollNumber: '47' },
  { id: 's48', name: 'Ayaz Muhammad', rollNumber: '48' },
  { id: 's49', name: 'Malak Saad Tanoli', rollNumber: '49' },
  { id: 's50', name: 'Muhammad Bilal', rollNumber: '50' },
  { id: 's51', name: 'Muhammad Khalid', rollNumber: '51' },
  { id: 's52', name: 'Tausif Ullah', rollNumber: '52' },
  { id: 's53', name: 'Daniyal Abbas', rollNumber: '53' },
  { id: 's54', name: 'Ahmad Hashim', rollNumber: '54' },
  { id: 's55', name: 'Shehbaz Khan', rollNumber: '55' },
  { id: 's56', name: 'Muhammad Israr Khan', rollNumber: '56' },
  { id: 's57', name: 'Atif Khan', rollNumber: '57' },
  { id: 's58', name: 'Farhadnoor', rollNumber: '58' },
  { id: 's59', name: 'Saad Khan', rollNumber: '59' },
  { id: 's60', name: 'Shahsawar Ahmad Khan', rollNumber: '60' },
  { id: 's61', name: 'Muhammad Usman', rollNumber: '61' },
  { id: 's62', name: 'Abdullah Khan', rollNumber: '62' },
  { id: 's63', name: 'Muhammad Ahsan', rollNumber: '63' },
  { id: 's64', name: 'Imran Jehangir', rollNumber: '64' },
  { id: 's65', name: 'Saud Ur Rahman', rollNumber: '65' },
  { id: 's66', name: 'Muhammad Bilal (66)', rollNumber: '66' },
  { id: 's67', name: 'Kiramat Ali Khan', rollNumber: '67' },
  { id: 's68', name: 'Muhammad Israr', rollNumber: '68' },
  { id: 's69', name: 'Muhammad Usman Sidiqi', rollNumber: '69' },
  { id: 's70', name: 'Adnan Khan', rollNumber: '70' },
  { id: 's71', name: 'Haseen Jan', rollNumber: '71' },
  { id: 's72', name: 'Muhammad Waqas', rollNumber: '72' },
  { id: 's73', name: 'Khayam Zaman', rollNumber: '73' },
  { id: 's74', name: 'Nasir Khan', rollNumber: '74' },
  { id: 's75', name: 'Syed Talha', rollNumber: '75' },
  { id: 's76', name: 'Ashraf Ali', rollNumber: '76' },
  { id: 's77', name: 'Irshad Ahmad', rollNumber: '77' },
  { id: 's78', name: 'Hamza Maqsood', rollNumber: '78' },
  { id: 's79', name: 'Zain Khan', rollNumber: '79' },
  { id: 's80', name: 'Muhammad Umar', rollNumber: '80' },
  { id: 's81', name: 'Atif Ullah', rollNumber: '81' },
  { id: 's82', name: 'Farman Ullah', rollNumber: '82' },
  { id: 's83', name: 'Asad Ihsan', rollNumber: '83' },
  { id: 's84', name: 'Farhan Ullah', rollNumber: '84' },
  { id: 's85', name: 'Atta Ur Rehman', rollNumber: '85' },
  { id: 's86', name: 'Muhammad Dawood', rollNumber: '86' },
  { id: 's87', name: 'Saim Mahmood', rollNumber: '87' },
  { id: 's88', name: 'Syed Mehmood Ahmad Shah', rollNumber: '88' },
  { id: 's89', name: 'Hizbullah', rollNumber: '89' },
  { id: 's90', name: 'Muhammad Anfal', rollNumber: '90' },
  { id: 's91', name: 'Hashim Hussain', rollNumber: '91' },
  { id: 's92', name: 'Muhammad Hamza', rollNumber: '92' },
  { id: 's93', name: 'Muhammad Afaq Alam', rollNumber: '93' },
  { id: 's94', name: 'Mekail Khan', rollNumber: '94' },
  { id: 's95', name: 'Akhtar Rahman', rollNumber: '95' },
  { id: 's96', name: 'Zahoor Ahmad', rollNumber: '96' },
  { id: 's97', name: 'Muhammad Rahim', rollNumber: '97' },
  { id: 's98', name: 'Muhammad Yaseen Durrani', rollNumber: '98' },
  { id: 's99', name: 'Eric Nazir Bhatti', rollNumber: '99' },
  { id: 's100', name: 'Adil Khan', rollNumber: '100' },
  { id: 's101', name: 'Muhammad Abdullah', rollNumber: '101' },
  { id: 's102', name: 'Habib Ullah Khan', rollNumber: '102' },
  { id: 's103', name: 'Ihtesham Khan', rollNumber: '103' },
  { id: 's104', name: 'Muhammad Usman (104)', rollNumber: '104' },
  { id: 's105', name: 'Muhammad Yahya Shah', rollNumber: '105' },
  { id: 's106', name: 'Hameed Ullah', rollNumber: '106' },
  { id: 's107', name: 'Hassan Aimal Shah', rollNumber: '107' },
  { id: 's108', name: 'Qazi Muhammad Zakariya', rollNumber: '108' },
  { id: 's109', name: 'Fawad Ali Khan', rollNumber: '109' },
  { id: 's110', name: 'Hammad Elahi', rollNumber: '110' },
  { id: 's111', name: 'Muhammad Aslam', rollNumber: '111' },
  { id: 's112', name: 'Nouman Ashraf', rollNumber: '112' },
  { id: 's113', name: 'Arsalan Asif Lone', rollNumber: '113' },
  { id: 's114', name: 'Muhammad Nouman', rollNumber: '114' },
  { id: 's115', name: 'Muhammad Adil Mabood', rollNumber: '115' },
  { id: 's116', name: 'Saud Ur Rahman (116)', rollNumber: '116' },
  { id: 's117', name: 'Ibrar Ahmad Khan', rollNumber: '117' },
  { id: 's118', name: 'Muhammad Hammad', rollNumber: '118' },
  { id: 's119', name: 'Suliman Khan', rollNumber: '119' },
  { id: 's120', name: 'Muhammad Adnan', rollNumber: '120' },
  { id: 's121', name: 'Haseen Afzal', rollNumber: '121' },
  { id: 's122', name: 'Ibrar Hussain', rollNumber: '122' },
  { id: 's123', name: 'Safi ullah', rollNumber: '123' },
  // English Department Combined (22 Students)
  ...Array.from({ length: 22 }, (_, i) => ({
    id: `eng-${i + 1}`,
    name: `English Dept Student ${i + 1}`,
    rollNumber: `E-${i + 1}`,
  })),
  // Sociology Department Combined (22 Students)
  ...Array.from({ length: 22 }, (_, i) => ({
    id: `soc-dept-${i + 1}`,
    name: `Sociology Dept Student ${i + 1}`,
    rollNumber: `S-${i + 1}`,
  })),
];
